### ISSUE TITLE
Flatten folders

### ISSUE THREAD

**Issue by DavidLeoni** [riccardomenini/Homework1#1]
Buondì

ho visto che hai copiato la cartella `min-cmake-prj-master`  come sotto cartella, ma questo è problematico perchè poi es. ti ritrovi con file `.gitignore` uno dentro l'altro, e se qualc'un'altro vuole riusare il tuo repo è meglio avere una struttura simile. 

Quindi cerca di avere una struttura tipo

```
src/
test/
README.md
```

David

**Comment by riccardomenini** [comment]
Buonasera @DavidLeoni,
dovrei essere riuscito a sistemare. Grazie per il consiglio.
Riccardo
