### ISSUE TITLE
Richieste

### ISSUE THREAD

**Issue by riccardomenini** [riccardomenini/Homework1#14]
@DavidLeoni,
avrei due questioni di carattere organizzativo: 
-quando dobbiamo consegnare, in linea di massima la seconda parte dell'Homework?
-sul foglio "vostre REPL" presente sul moodle non appare la versione del mio progetto nonostante io abbia taggato le versioni con git.
Grazie e buona giornata.

**Comment by DavidLeoni** [comment]
1) quando ce l'avete, me la mandate - possibilmente entro un paio di settimane, anche perchè altrimenti il lavoro si accumula
2) su github non figurano releases, credo che hai messo solo le tag in locale, devi pusharle sul github:

```bash
git push origin v1.0.0  
```
![image](https://user-images.githubusercontent.com/628313/116661984-7dc1b480-a995-11eb-98ea-0e0ff96357cc.png)

**Comment by riccardomenini** [comment]
Va bene grazie. Devo pusharle tutte una a una o posso pushare solo l'ultima per fare in modo che vengano pushate tutte?

**Comment by DavidLeoni** [comment]
tutte
