### ISSUE TITLE
Delucidazioni

### ISSUE THREAD

**Issue by riccardomenini** [riccardomenini/Homework1#5]
@DavidLeoni,
Vorrei alcune delucidazioni sulla consegna: la funzione init deve controllare i vincoli e la funzione set deve permettere di modificare le misure e poi controllare se tali modifiche sono compatibili. Io pensavo di creare la funzione set e poi all'interno di essa chiamare la funzione init per controllare se le misure sono compatibili, senza creare del nuovo codice che svolga la stessa funzione. Può essere un approccio corretto? 

Inoltre sulla consegna viene specificato di creare varie funzioni set che modifichino i vari parametri. Io ne ho fatto una sola settarli tutti. Può andare bene lo stesso?

Infine ho un paio di domande su git. Ogni volta che eseguo mainEntry git rileva due modifiche nella cartella build. Da quello che ho capito dovrei inserire i file che vengono modificati nel file .gitignore ma non riesco a farlo. L'altra domanda è invece strettamente legata a GitHub: quando lancio il comando push da terminale, se entro su GitHub mi mostra una Pull request. Io avevo capito a lezione che solitamente le Pull request si hanno quando altri tentano di modificare la repository: mi chiedo quindi come questo sia possibile.

Grazie per l'attenzione e scusi il disturbo,
Riccardo Menini

**Comment by DavidLeoni** [comment]
>  la funzione init deve controllare i vincoli e la funzione set deve permettere di modificare le misure e poi controllare se tali modifiche sono compatibili. Io pensavo di creare la funzione set e poi all'interno di essa chiamare la funzione init per controllare se le misure sono compatibili, senza creare del nuovo codice che svolga la stessa funzione. Può essere un approccio corretto?

Meglio ancora, fai una funzione check  e poi la richiami da init e set

> Inoltre sulla consegna viene specificato di creare varie funzioni set che modifichino i vari parametri. Io ne ho fatto una sola settarli tutti. Può andare bene lo stesso?

meglio farne una per parametro - lo so è un po' noioso, ma purtroppo il codice  "boilerplate" fa parte della vita. 

> Infine ho un paio di domande su git. Ogni volta che eseguo mainEntry git rileva due modifiche nella cartella build. Da quello che ho capito dovrei inserire i file che vengono modificati nel file .gitignore ma non riesco a farlo. 

mmm in teoria non dovrebbe rilevare nulla da build. Forse per sbaglio l'avevi versionata e poi hai aggiunto il gitignore? Per risolvere, potresti provare  a fare `git rm --cached build`

> L'altra domanda è invece strettamente legata a GitHub: quando lancio il comando push da terminale, se entro su GitHub mi mostra una Pull request. Io avevo capito a lezione che solitamente le Pull request si hanno quando altri tentano di modificare la repository: mi chiedo quindi come questo sia possibile.

Credo che ti mostri se _vuoi_ fare una pull request, non è detto che _devi_ farla :-)

**Comment by DavidLeoni** [comment]
per essere più specifici sulle pull request, l'idea è che github ti offre di fare facilmente via web una merge da altri branch a main, magari facendoci anche dei controlli extra che vedremo meglio più avanti.

**Comment by riccardomenini** [comment]
@DavidLeoni 

> Meglio ancora, fai una funzione check e poi la richiami da init e set

> Inoltre sulla consegna viene specificato di creare varie funzioni set che modifichino i vari parametri. Io ne ho fatto una sola settarli tutti. Può andare bene lo stesso?

Ok ho fatto nel modo che si vede qui su GitHub. Può andare bene?

> mmm in teoria non dovrebbe rilevare nulla da build. Forse per sbaglio l'avevi versionata e poi hai aggiunto il gitignore? Per risolvere, potresti provare a fare git rm --cached build
Grazie mille, in questo modo ho risolto.

> Credo che ti mostri se vuoi fare una pull request, non è detto che devi farla :-)
Ho provato a non farla ma le modifiche in questo caso non si vedono nella sezione code di Github e i commit non sono visibili nella relativa sezione.

Grazie per l'attenzione e per la tempestiva risposta,
Riccardo Menini

**Comment by DavidLeoni** [comment]
>  Inoltre sulla consegna viene specificato di creare varie funzioni set che modifichino i vari parametri. Io ne ho fatto una sola settarli tutti. Può andare bene lo stesso?
> Ok ho fatto nel modo che si vede qui su GitHub. Può andare bene?

ehm no, vedo che chiedi input all'utente con `cin`, l'idea invece è che il parametro sia passato con gli argomenti della funzione.

>    Credo che ti mostri se vuoi fare una pull request, non è detto che devi farla :-)

> Ho provato a non farla ma le modifiche in questo caso non si vedono nella sezione code di Github e i commit non sono visibili 
> nella relativa sezione.

Immagino starai facendo delle push nel branch fix2:  per vederle nel branch main prima o poi dovrai fare una merge in main. Per farlo hai due opzioni: o fai una merge in locale da fix2 in merge  sulla tua macchina, e poi pushi su main, oppure usi l'interfaccia delle pull request che ti offre github.

**Comment by DavidLeoni** [comment]
Altra cosa: la `menini_check(device)` fa delle stampe, ma in realtà l'unica cosa che dovrebbe contare è il parametro di ritorno, che dovresti sempre controllare quando la chiami, cosa che al momento non viene fatta nelle set. Ricordati che anche le set possono fallire e devono poter segnalare l'errore all'esterno ritornando un valore di errore.  E qua si pone il problema che se chiami la `check` dopo che hai già modificato il device con dati passati dall'utente , di fatto è inutile, perchè a quel punto il device potrebbe già essere corrotto.

**Comment by riccardomenini** [comment]
Grazie mille,
Provvedo subito alle modifiche.
